### ISSUE TITLE
​[Bug]: Intermittent High Latency (1-3 mins delay) in Event Processing - v7.0.0-rc.9

### ISSUE THREAD

**Issue by AmilaPrabathKumara** [WhiskeySockets/Baileys#2171]
**Describe the bug**
I am experiencing sporadic but significant delays in receiving events (specifically `messages.upsert`).
The issue is **not constant**; sometimes the bot works perfectly with real-time responses. However, at random intervals, the event processing lags significantly.

* **Delay Duration:** The lag varies between **1 to 3 minutes**.
* **Frequency:** It happens intermittently. The bot functions normally for a while, then enters this "slow mode" temporarily before recovering.

During these lag periods, the socket connection appears to remain open, but incoming messages are not emitted by the `messages.upsert` event until the delay passes.

**Steps to Reproduce**
1.  Run the bot with `v7.0.0-rc.9`
2.  Use the bot normally.
3.  Observe that occasionally, incoming messages take **1-3 minutes** to appear in the logs/console.
4.  After the delay, the queued events usually flush through automatically.

**Expected behavior**
Messages should be processed in real-time consistently, without intermittent spikes in latency.

**Comment by adarshmadrecha** [comment]
I believe https://github.com/WhiskeySockets/Baileys/pull/2179 should fix this.

**Comment by YonkoSam** [comment]
@adarshmadrecha No, I don’t think this is related. The issue here seems to be the mutex being blocked or events not being flushed.

**Comment by joe-arms** [comment]
@adarshmadrecha already updated but still experiencing the problem

**Comment by TristanCage** [comment]
yes , brother you are not the only facing this issues , at first when I noticed the lag I thought the issue was coming from the fact I'm using sqlAuthstate with only creds.json , then I switched back to multiFileAuthstate, yet the issues persist, the thing feels like the bot just decides to run slow at its own chosen time 1 - 3 minutes delay before message upset fires
